services:
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000

#version: '3'
#services:
#  prometheus:
#    image: prom/prometheus
#    container_name: prometheus
#    volumes:
#      - ./prometheus.yml:/etc/prometheus/prometheus.yml
#    command:
#      - '--config.file=/etc/prometheus/prometheus.yml'
#    ports:
#      - '9090:9090'
#  grafana:
#    container_name: grafana
#    image: grafana/grafana:6.6.2
#    environment:
#      - GF_SECURITY_ADMIN_USER=admin
#      - GF_SECURITY_ADMIN_PASSWORD=admin
#      - GF_USERS_ALLOW_SIGN_UP=false
#    volumes:
#      - ~/docker/grafana/data:/var/lib/grafana
#      - ~/docker/grafana/provisioning:/etc/grafana/provisioning
#    ports:
#      - '9091:3000'
#    depends_on:
#      - prometheus